# reference: https://docs.npmjs.com/trusted-publishers#for-github-actions

name: Publicar no NPM

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes de segurança
        run: npm test

      - name: Publicar no Registro NPM
        run: npm publish --access public --provenance
